### ISSUE TITLE
Transition by untranslated status name not working

### ISSUE THREAD

**Issue by brutto** [lesstif/php-JiraCloud-RESTAPI#15]
In [doc](https://github.com/lesstif/php-JiraCloud-RESTAPI#perform-a-transition-on-an-issue) for issue transition was said to use `Transition::setUntranslatedName()` method  for "JIRA with local language profiles". 

But if you use it transition id calculated wrong: **Instead of transition id used status id** So you get errors like ` {"errorMessages":["Transition id '<real-status-id>' is not valid for this issue."],"errors":{}}`.

Problem in `IssueService::findTransitonIdByUntranslatedName`.

PS: Also problem with strict types for Transition model:
```php
$transition = new Transition();
$transition->transition = [];
$transition->setTransitionId('111'); // Resolve
```
Init transition property because of 
```
Typed property JiraCloud\Issue\Transition::$transition must not be accessed before initialization" at src/Issue/Transition.php line 47
```

**Comment by lesstif** [comment]
Hi @brutto, it was fixed by [#18](https://github.com/lesstif/php-JiraCloud-RESTAPI/commit/a0ffd9748135e00a0c3101584069a7d740143458#diff-e2eabb148e7868d521290f19412e071fa930fdbdd8ce0c41e7ee218f00e1f297) commit. 
Thank you!
