### ISSUE TITLE
Class "JiraCloud\JiraCloudApiServiceProvider" not found

### ISSUE THREAD

**Issue by pcboii** [lesstif/php-JiraCloud-RESTAPI#17]
Hi, getting the following error on composer install, on laravel project.

Please note, JiraCloud\JiraCloudServiceProvider::class also added to app/config.app under providers array. 

--

ERROR

In ProviderRepository.php line 208:
Class "JiraCloud\JiraCloudApiServiceProvider" not found  
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by pcboii** [comment]
Possibly related/caused by
https://github.com/lesstif/php-JiraCloud-RESTAPI/issues/9

**Comment by lesstif** [comment]
Hi @pcboii I released a new version.

have a great day!
