### ISSUE TITLE
ADF

### ISSUE THREAD

**Issue by DamienHarper** [lesstif/php-JiraCloud-RESTAPI#2]
Hi @lesstif and thanks for this new project dedicated to Jira API v3.

As of now, I use your very good and powerful library `lesstif/php-jira-rest-client` but recently encountered issues using Jira API v3 (https://github.com/lesstif/php-jira-rest-client/issues/458 for example) mostly regarding ADF support (Atlassian Document Format).

Recently, I built a library to build, parse and convert ADF to other formats (HTML only as of now, other formats in the future) and I thought you might be interested to use it inside `php-jira-rest-client`. I think it might help, for example, to provide more freedom/flexibility adding comments to worklogs, description to issues etc.

Here is the repo: https://github.com/DamienHarper/adf-tools

As of now, the code is well tested but there is no documentation yet (will work on it soon) but tests are quite demonstrative.

I'm very happy to see you're working on a new client dedicated to Jira API v3 which brings better support to ADF, though you may have a look to my library, it should avoid you to implement ADF building/parsing again.

Feel free to contact me if you’re interested, I’d be glad to help.

**Comment by lesstif** [comment]
Hi @DamienHarper.

I'd struggled to analyze and implement the ADF, so I just started it without any design or architecture.
But your ADF implementation looks great and well structured, so I will throw out my code into the trashcan and import it into my new V3 API repository.

Thank you so much informed to me and developing a fantastic project.  :)

I will reach out to you if I have any questions or suggestions.

**Comment by DamienHarper** [comment]
@lesstif I close this issue for now, let me know if you need help ;)

**Comment by DamienHarper** [comment]
@lesstif I released `adf-tools` v1.0.0 so you can update your `composer.json` to target the stable release (no BC)
