### ISSUE TITLE
JiraRestApiServiceProvider not comply with psr-4 + monolog dependency issue

### ISSUE THREAD

**Issue by esseremmerik** [lesstif/php-JiraCloud-RESTAPI#25]
When using this version inside Laravel 9.x, it will output an error when finalising the autodiscover.
 
Class JiraCloud\JiraCloudServiceProvider located in ./vendor/lesstif/jira-cloud-restapi/src/JiraRestApiServiceProvider.php does not comply with psr-4 autoloading standard. Skipping.

Version 1.2 of this package also causes dependency error with monolog v3.

Problem 1
    - monolog/monolog 2.0.0-beta1 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
    - monolog/monolog[2.0.0-beta2, ..., 2.0.2] require php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
    - laravel/framework[v9.19.0, ..., 9.x-dev] require monolog/monolog ^2.0 -> satisfiable by monolog/monolog[2.0.0-beta1, ..., 2.x-dev].
    - You can only install one version of a package, so only one of these can be installed: monolog/monolog[2.0.0-beta1, ..., 2.x-dev, 3.0.0-RC1, ..., 3.x-dev].
    - lesstif/jira-cloud-restapi 1.2 requires monolog/monolog ^3.0 -> satisfiable by monolog/monolog[3.0.0-RC1, ..., 3.x-dev].
    - Root composer.json requires lesstif/jira-cloud-restapi ^1.2 -> satisfiable by lesstif/jira-cloud-restapi[1.2].
    - Root composer.json requires laravel/framework ^9.19 -> satisfiable by laravel/framework[v9.19.0, ..., 9.x-dev].

**Comment by lesstif** [comment]
Hi @esseremmerik I'm so sorry for the late reply.

It seems very similar #24 and originated from #8.

I will search for a solution how I can fix it.

**Comment by lesstif** [comment]
It's fixed at [v1.4](https://github.com/lesstif/php-JiraCloud-RESTAPI/tree/1.4)
