### ISSUE TITLE
Fix adf-tool version

### ISSUE THREAD

**Issue by brutto** [lesstif/php-JiraCloud-RESTAPI#28]
In version [1.2](https://github.com/lesstif/php-JiraCloud-RESTAPI/blob/1.2/composer.json) adf-tools at `dev-master` dependency. Please fix it to latest tag for composer minimum-stability issues.

**Comment by lesstif** [comment]
Hi @brutto. I released [1.3](https://github.com/lesstif/php-JiraCloud-RESTAPI/releases/tag/1.3) a few minutes ago.

have a great today!
