### ISSUE TITLE
WorkLog::$comment

### ISSUE THREAD

**Issue by bkdotcom** [lesstif/php-JiraCloud-RESTAPI#30]
> Uncaught exception 'Error' with message Typed property JiraCloud\Issue\Worklog::$comment must not be accessed before initialization

It appears comment isn't being set... (via `IssueService::getWorklog`) when I try to get the comment via `$worklog->comment` I get the above error.

re how to use `worklog::setComment()` ?? ...  the documentation in README.md seems to be outdated

**Comment by lesstif** [comment]
Hi @bkdotcom 
Thank you for reaching out to me.

I updated the sample and manual. You can [check it out here](https://github.com/lesstif/php-JiraCloud-RESTAPI#add-worklog-in-issue).
