### ISSUE TITLE
IssueService / JsonMapper uncaught exception

### ISSUE THREAD

**Issue by bkdotcom** [lesstif/php-JiraCloud-RESTAPI#31]
issueService->search results in uncaught exception

Exception, JSON property "environment" in class "JiraCloud\Issue\IssueField" is an object and cannot be converted to a string,

Thrown in JsonMapper

Logger output:
> Curl POST: https://mydomain.atlassian.net/rest/api/3/search JsonData={"jql":"(worklogDate > \"2022-12-05\" AND worklogDate < \"2022-12-19\" AND worklogAuthor = currentUser()) ORDER BY created DESC","startAt":0,"maxResults":100,"fields":["*all"],"expand":[],"validateQuery":true}

**Comment by lesstif** [comment]
@bkdotcom I'm so sorry late reply.

Could you change the $environment in the JiraCloud\Issue\IssueField as the array type and rerun, please?

If it works well, I will change the field type and release a new version.

```php
class IssueField implements \JsonSerializable
{
//public ?string $environment;
public ?array $environment;
```

**Comment by krokovicsmate** [comment]
@lesstif i had a same error too and changing to `?array` fixed it. 

It works well. Thanks.
