### ISSUE TITLE
jsonSerialized error in ADF

### ISSUE THREAD

**Issue by krokovicsmate** [lesstif/php-JiraCloud-RESTAPI#34]
Hi!

When i want to jsonSerialized the description of an issue i get the following error:

`Typed property JiraCloud\ADF\AtlassianDocumentFormat::$document must not be accessed before initialization`

I want this cuz i need to convert to HTML the ADF.
My Code:

`(new DocumentExporter(Document::load($projectTask->fields?->description->jsonSerialize())))->export()`

Anyone has the same issue? Or has a prettier solution to convert the description to HTML?

Thanks for the help.

**Comment by lesstif** [comment]
Hi @krokovicsmate .

Fir of all, I fixed the typed property initializing issue.

Second, I believe that using the renderedFields is a great option for this case like the below code.

```php
$issueService = new IssueService();

$issue = $issueService->get('TEST-149', ['expand' => 'renderedFields']);

// You can get the rendered HTML field
print_r($issue->renderedFields['description']);
```

Thanks!

**Comment by krokovicsmate** [comment]
@lesstif Thanks the fix.

Yes i found out the renderedFIelds is getting back the description in html, but only unfortunatly the description get in html. 
The comment body and the work log comment is still in array ADF format.

Anyway i can doit now. Thanks!

**Comment by lesstif** [comment]
@krokovicsmate If you use the expand param when you fetch comments through REST API, you can get the HTML comments.

```php
$issueService = new IssueService();
$comments = $issueService->getComments($issueKey, ['expand' => 'renderedBody']);

foreach ($comments->comments as $c) {
    var_dump($c->renderedBody);
}
```

**Comment by krokovicsmate** [comment]
@lesstif I find that too after i wrote :D. Only one palce where i can't find the rendered version is the work-log comments. There not have a rendered expand options, according to the api description.
