### ISSUE TITLE
"Class "JiraCloud\ADF\Attachment" not found"

### ISSUE THREAD

**Issue by Johannes0501** [lesstif/php-JiraCloud-RESTAPI#38]
Hi, 

The class JiraCloud\ADF\Attachment does not exist.

**Comment by lesstif** [comment]
Hi @Johannes0501 Could you share the code with me, please?

**Comment by cfreak** [comment]
have the same Problem

**Comment by cfreak** [comment]
The Problem is in AttachmentService there is a wrong use.

The use should be:

`use JiraCloud\Issue\Attachment;`

instead of:

`use JiraCloud\ADF\Attachment;`

**Comment by cfreak** [comment]
i have made a pull request, please accept it

**Comment by lesstif** [comment]
Hi @cfreak @Johannes0501 got it. see #41
