### ISSUE TITLE
Linking issues does not work

### ISSUE THREAD

**Issue by bertoost** [lesstif/php-JiraCloud-RESTAPI#54]
Hi,

When I try to link issues it doesn't work properly.
As per docs, I have set the issue key for inward and outward, but then this error occurs

```
Cannot auto-initialize an array inside property JiraCloud\IssueLink\IssueLink::$inwardIssue of type JiraCloud\Issue\Issue"
```
I also tried with setting the Issue object itself;

```php
$issueLink->inwardIssue = $issueFrom;
//....
```

but then I get a "wrong payload" response. Probably because it's way to big with all those issue fields.

Also a Comment seems to be required on a issue link, while this should be optional.

Regards, Bert

**Comment by bertoost** [comment]
For now I have managed to use a raw data, to get it working again.

```php
$data = [
    'inwardIssue' => [
        'key' => $from->key,
    ],
    'outwardIssue' => [
        'key' => $to->key,
    ],
    'type' => [
        'name' => $typeName,
    ],
];
```

**Comment by lesstif** [comment]
Hi @bertoost Sorry for the late reply.

I'm so sorry that IssueLink features have not been suitably implemented for REST v3.
I'll rewrite this feature next week.

**Comment by lesstif** [comment]
Hi @bertoost I just pushed the new code.
check out [this example code](https://github.com/lesstif/php-JiraCloud-RESTAPI#create-issue-link) please.

**Comment by bertoost** [comment]
Thanks @lesstif ! It works like a charm now.
