### ISSUE TITLE
Allow nullable values for customfields

### ISSUE THREAD

**Issue by bertoost** [lesstif/php-JiraCloud-RESTAPI#55]
Hi there,

A value for a customfield must be settable as NULL. For example; when you want to clear the flag-impediment field, you need to pass NULL instead of any value.

```php
$issueField = new IssueField(true);
$issueField->addCustomField('customfield_xxxxx', null);
```

The IssueField does not accept NULL values.

File: `src/Issue/IssueField.php`

Change
```php
public function addCustomField(string $key, string|int|float|array|Document $value): static
```
To
```php
public function addCustomField(string $key, string|int|float|array|Document $value = null): static
```

Ps. when I am finished, I will create a PR for this.

Regards, Bert

**Comment by lesstif** [comment]
Hi @bertoost I'll wait for your PR.
Thanks!

**Comment by bertoost** [comment]
I see it's recently already being added via #48
