### ISSUE TITLE
Too few arguments to function

### ISSUE THREAD

**Issue by kedesignzcom** [lesstif/php-JiraCloud-RESTAPI#59]
Error:
Too few arguments to function JiraCloud\JiraClient::curlPrepare(), 2 passed in /Users/dev/PhpstormProjects/internal_project/vendor/lesstif/jira-cloud-restapi/src/JiraClient.php on line 330 and exactly 3 expected

Notes:
- Attempting to add attachment to issue fails with the following error.
- JIRA API Username/Token in use, no cookie file.

Environment:
- PHP 8.1.17
- Laravel 10.12.0

**Comment by lesstif** [comment]
Hi @kedesignzcom It's fixed on the 1.61.

Thanks!
