### ISSUE TITLE
Quoting in JqlQuery::addInExpression breaks search by issue ID

### ISSUE THREAD

**Issue by kito-inv** [lesstif/php-JiraCloud-RESTAPI#64]
Hi, I was trying to search jira issues by ID but the addInExpression method quotes the values passed in the array and generates an invalid query.

### How to reproduce
```
$jqlQuery = new JqlQuery();
$jqlQuery->addInExpression(
    JqlQuery::FIELD_ISSUE_KEY,
    [1,2]
);
$jqlQuery->getQuery(); // outputs "issueKey" in ("1","2") but it should be "issueKey" in (1,2)
```
This query results in this error from the Jira API:
```
{
    "errorMessages": [
        "The issue key '1' for field 'issueKey' is invalid.",
        "The issue key '2' for field 'issueKey' is invalid."
    ],
    "warningMessages": []
}
```

I have confirmed that the request works without the quotes around the values

**Comment by lesstif** [comment]
Hi @kito-inv I changed the function signature to allow additional param for non-quoting.
you can use the below code for that.

```php
 $jqlQuery->addNotInExpression(
                JqlQuery::FIELD_ISSUE_KEY,
                [1,2],
                JqlQuery::KEYWORD_AND,
                false
            );
```
