### ISSUE TITLE
Issue retrieving organisation

### ISSUE THREAD

**Issue by thery-dh** [lesstif/php-JiraCloud-RESTAPI#76]
I have encountered two issues while trying to get an organization from JiraServiceDesk:

- The ServiceDeskClient used by OrganisationService appends `servicedeskapi` resulting in a duplicate in the uri: https://github.com/lesstif/php-JiraCloud-RESTAPI/blob/main/src/ServiceDesk/ServiceDeskClient.php#L31
- The links property returned by Jira is a json object not an array, resulting in an Organisation() mapping error

Both issues have been fixed in the following PR:
https://github.com/lesstif/php-JiraCloud-RESTAPI/pull/75

Would love to get this merged :-)

**Comment by lesstif** [comment]
Hi @thery-dh thank you for your contribution!
have a good day.
