### ISSUE TITLE
Monolog v3 breaking change for NoOperationMonologHandler::write method

### ISSUE THREAD

**Issue by nanodocumet** [lesstif/php-JiraCloud-RESTAPI#8]
Hello,

Thanks for putting this library together!

The `composer.json` has `"monolog/monolog": "^2.0|^3.0"` in [here](https://github.com/lesstif/php-JiraCloud-RESTAPI/blob/main/composer.json#L11) which could install the `3.x` Monolog versions. Monolog `3.x` has a breaking change in the `write` method signature for the class `AbstractProcessingHandler` as seen in [here](https://github.com/Seldaek/monolog/compare/2.8.0...3.0.0#diff-374a6357e3f89f4b70f66a1606f8bd74c7e2bd39dce237578d134d86beb420c1L58). This means that the current definition for `NoOperationMonologHandler::write` is not supporting Monolog `3.x` from [here](https://github.com/lesstif/php-JiraCloud-RESTAPI/blob/main/src/NoOperationMonologHandler.php#L16) but only Monolog `2.x`.

This issue only becomes visible when setting the `jiraLogEnabled` to `false` in the Configuration (which goes through this flow in [here](https://github.com/lesstif/php-JiraCloud-RESTAPI/blob/6eeb0c7506f4048e7f83249f480760311eb37bb9/src/JiraClient.php#L93-L96)). In order to work around it I explicitly set the Monolog version in my composer.json file.

Not sure what else is using any specific implementations of Monolog, but it might make sense to drop the `2.x` support in favor of the `3.x` release. Thoughts?

**Comment by lesstif** [comment]
Hi @nanodocumet Thank you for informed to me.
Could you Ok if I drop the support monolog v2.0, please?
If you are ok, I will modify NoOperationMonologHandler to be suitable for Monolog v3.

**Comment by brutto** [comment]
@lesstif monolog v2 not compatible with v3, so i think you can drop v2 support with next release.

**Comment by nanodocumet** [comment]
@lesstif sure, dropping support for Monolog v2 should be a good path to go here. Sorry for the late response
