### ISSUE TITLE
Incorrect filename (PSR-4)

### ISSUE THREAD

**Issue by jaakon** [lesstif/php-JiraCloud-RESTAPI#9]
Hello,

thanks for this library. I've just switched to this new version and encounter an issue:

The class `JiraCloud\JiraCloudServiceProvider` has the filename `JiraRestApiServiceProvider.php` and therefore does not comply with psr-4 autoloading standard.

I guess, it just needs to be renamed :)

UPDATE: The name also doesn't match up with the laravel providers in the composer.json: `JiraCloudApiServiceProvider`

**Comment by lesstif** [comment]
Hi @jaakon Thank you for informed to me.

I will change it to comply with the PSR-4 this weekend and release a new version. :)
